import type { Metadata } from 'next';

const modules = [
  {
    status: 'Live soon',
    title: 'Content studio',
    description: 'Draft social posts, newsletter snippets, and short-form scripts from Research Engine outputs.',
    bullets: ['Channel presets (IG, X, newsletter)', 'Tone sliders per persona', 'Asset attachments from Showroom']
  },
  {
    status: 'Beta',
    title: 'Scheduling & approvals',
    description: 'Manage queues with Strategy Board sign-off and Ethics checks before publishing.',
    bullets: ['Approval workflows', 'Calendar view', 'Link back to Prompt Lab variants']
  },
  {
    status: 'Planned',
    title: 'Performance feedback',
    description: 'Pull analytics from social platforms to refine prompts and content planning.',
    bullets: ['Metrics ingested to Supabase', 'Automatic prompt tuning suggestions', 'Historian recap of campaigns']
  }
] as const;

const automations = [
  {
    status: 'Live',
    title: 'n8n pipelines',
    description: 'Automate posting, archiving, and fallback scheduling through n8n.',
    bullets: ['Multi-channel fan-out', 'Retry logic with alerts', 'Archive outputs in Historian']
  },
  {
    status: 'Beta',
    title: 'Social A/B engine',
    description: 'Experiment with content variations generated by Prompt Lab and tracked by the router.',
    bullets: ['Variant scoring dashboards', 'Persona weighting for results', 'Auto-promote winners']
  },
  {
    status: 'Planned',
    title: 'Community responses',
    description: 'Monitor replies and route them to Strategy Board, Ops, or Ethics as needed.',
    bullets: ['Sentiment tagging', 'Escalation workflows', 'Feed back into Research Engine']
  }
] as const;

export const metadata: Metadata = {
  title: 'Social Playground — VibeMixer',
  description: 'Plan, approve, and automate NarcoNations social storytelling with governance baked in.'
};

export default function SocialPlaygroundPage() {
  return (
    <main>
      <section className="hero">
        <span className="tagline">Social Playground</span>
        <h1>Coordinate NarcoNations storytelling across every channel</h1>
        <p>
          Draft content, gather approvals, and schedule releases with automation. Social Playground turns research insights into
          campaigns while keeping Ethics informed.
        </p>
        <div className="actions">
          <span className="pill">Content studio</span>
          <span className="pill">Approvals</span>
          <span className="pill">Automation</span>
        </div>
      </section>

      <section className="section">
        <header className="section-header">
          <span className="section-eyebrow">Modules</span>
          <h2 className="section-title">From draft to scheduled drop</h2>
          <p className="section-subtitle">
            Use persona-aware workflows to keep copy on tone, assets on brand, and approvals transparent.
          </p>
        </header>
        <div className="feature-card-grid">
          {modules.map((card) => (
            <article className="feature-card" key={card.title}>
              <div className="feature-card-header">
                <span className="feature-card-eyebrow">{card.status}</span>
                <h3>{card.title}</h3>
              </div>
              <p>{card.description}</p>
              <ul>
                {card.bullets.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      <section className="section">
        <header className="section-header">
          <span className="section-eyebrow">Automation</span>
          <h2 className="section-title">Automate delivery and learning loops</h2>
          <p className="section-subtitle">
            Integrate n8n workflows, A/B testing, and community monitoring so Social Playground runs itself with oversight.
          </p>
        </header>
        <div className="feature-card-grid">
          {automations.map((card) => (
            <article className="feature-card" key={card.title}>
              <div className="feature-card-header">
                <span className="feature-card-eyebrow">{card.status}</span>
                <h3>{card.title}</h3>
              </div>
              <p>{card.description}</p>
              <ul>
                {card.bullets.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      <section className="feature-callout">
        <strong>Complete campaign visibility</strong>
        <p>
          Historian captures every post, approval, and metric. Strategy Board can review the entire lifecycle from spark to impact.
        </p>
      </section>
    </main>
  );
}
